# Generated by Django 3.2.4 on 2021-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Signup',
            fields=[
                ('Customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=200)),
                ('u_email', models.CharField(max_length=200, unique=True)),
                ('u_password', models.CharField(max_length=200)),
                ('w_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Helper_Signup',
            fields=[
                ('Helper_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=200)),
                ('u_email', models.CharField(max_length=200, unique=True)),
                ('u_password', models.CharField(max_length=200)),
                ('cur_stat', models.BooleanField(default=False)),
                ('total_success', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='works_by_helpers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='real_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('cid', models.ManyToManyField(to='logins.Customer_Signup')),
                ('hid', models.ManyToManyField(to='logins.Helper_Signup')),
                ('wid', models.ManyToManyField(to='logins.works_by_helpers')),
            ],
        ),
        migrations.AddField(
            model_name='helper_signup',
            name='u_work',
            field=models.ManyToManyField(to='logins.works_by_helpers'),
        ),
    ]
